wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.8
    cli_version: 0.16.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1702332985.256377
    t:
      1:
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.8.8
      5: 0.16.1
      8:
      - 1
      - 5
      13: darwin-x86_64
    framework: keras
